### ISSUE TITLE
Multiple authors

### ISSUE THREAD

**Issue by mrcnski** [matryer/xbar-plugins#1030]
I've made significant changes to one of the plugins, ranging from QoL improvements to major bug fixes.

Considering the scope of the changes (it's basically an overhaul), I'd like to add myself as an author, or at least a contributor. Does bitbar support multiple authors on a plugin? If so, then the Metadata section could be updated to reflect this. If not, what should I do? Upload a new plugin? The problem with that is that the original stays up, and it's quite buggy.

Your insight would be much appreciated -- thanks!

**Comment by gingerbeardman** [comment]
Multiple authors can be done like this: https://github.com/matryer/bitbar-plugins/blob/master/Dev/GitHub/notifications.30s.py

My thoughts are that most recent author would come first?

**Comment by m-cat** [comment]
Thanks @gingerbeardman! Are multiple entries for `<bitbar.author.github>` not supported? It doesn't matter so much to me, but it would be a nice enhancement.

**Comment by tresni** [comment]
Not today
