### ISSUE TITLE
re: Taskwarrior

### ISSUE THREAD

**Issue by lillian27** [matryer/xbar-plugins#1044]
FAO: (@christophruss)

Path to TW is assumed to be /usr/local/bin (and hardcoded in 2 places) causing exceptions on systems where this is not the case (e.g. TW installed into /opt/local/bin by MacPorts).

Perhaps examine expected binary locations at install time and use a known good path?  IDK if BitBar has any sort of pre-install hooks/dependency resolution for plugins or if altering plugin source on the fly is condoned.

In any case the bin path should probably be defined once and used throughout.

**Comment by gingerbeardman** [comment]
I guess most of these scripts assume use of brew.

You can edit the script yourself to fix.

However, I think a better solution would be to do `which task` for each external command required and then error check and store the result for use throughout the script.

`path_task = subprocess.check_output(['which', 'task'])` [L33](https://github.com/matryer/bitbar-plugins/blob/master/Lifestyle/taskwarrior.4m.py#L33) & [L67](https://github.com/matryer/bitbar-plugins/blob/master/Lifestyle/taskwarrior.4m.py#L67)
`path_python = subprocess.check_output(['which', 'python'])` [L42](https://github.com/matryer/bitbar-plugins/blob/master/Lifestyle/taskwarrior.4m.py#L42)
`path_python = subprocess.check_output(['which', 'defaults'])` [L161](https://github.com/matryer/bitbar-plugins/blob/master/Lifestyle/taskwarrior.4m.py#L161)

But I'm happy to assist and then you could make a pull request with your more universal/robust version of the script?
