### ISSUE TITLE
re: Daily Standup - Always showing ALERT_INDICATOR

### ISSUE THREAD

**Issue by RyanBeckett** [matryer/xbar-plugins#1080]
FAO: (@krishkumar) 

Three commits have been made, still showing ALERT_INDICATOR

![screen shot 2018-08-03 at 15 31 33](https://user-images.githubusercontent.com/4528659/43648451-5880c71a-9732-11e8-88ec-1d44fe1f3980.png)

**Comment by krishkumar** [comment]
Are you still facing this issue? 

I am releasing a new version soon. Might fix these issues.

**Comment by sprak3000** [comment]
Closing due to age and no further updates from author.
