### ISSUE TITLE
re: World Clock

### ISSUE THREAD

**Issue by johnkyle510** [matryer/xbar-plugins#1082]
FAO: (@asnodgrass)
Can I have EST be the time displayed on the menu bar?

**Comment by sprak3000** [comment]
@johnkyle510 

You would have to alter the plugin:

```
date -u +'%H:%M:%S UTC'
```

to 

```
date +'%H:%M:%S EST'
```

However, the plugin displays the various zones as offsets from UTC. Might look odd. If it meets your needs though, this is the change to make.
