### ISSUE TITLE
Plugin request

### ISSUE THREAD

**Issue by C4Wiz** [matryer/xbar-plugins#1094]
im looking for a plugin to check for a new version of makemkv, perhaps check the version numbers from https://www.makemkv.com/download/makemkv-sha-x.txt vs https://www.makemkv.com/download/old/makemkv-sha-x.txt

**Comment by gingerbeardman** [comment]
You can use a dedicated app such as https://www.corecode.io/macupdater/

**Comment by C4Wiz** [comment]
App is not on my mac

**Comment by C4Wiz** [comment]
If i knew how i would not have posted a request,
