### ISSUE TITLE
re: Instagram Stats

### ISSUE THREAD

**Issue by Cobra-Mafia** [matryer/xbar-plugins#1153]
FAO: (@JanGross)
Hello.
I would like to say that the plugin does not work.
Displays the following error.
http://prntscr.com/m0nhd1

**Comment by gingerbeardman** [comment]
You need to install at least the requests module in your Python

**Comment by Cobra-Mafia** [comment]
> You need to install at least the `requests` module in your Python

You can help me with this, I'm a layman.
I have python already installed.

**Comment by JanGross** [comment]
@Cobra-Mafia 
Try to run `pip install requests` and see if it solves the problem

**Comment by sprak3000** [comment]
No updates from author in over 4 years. Closing.
