### ISSUE TITLE
re: IP Address Info

### ISSUE THREAD

**Issue by monaronyc** [matryer/xbar-plugins#1163]
FAO: (@skhg)
Hi, loving your BitBar IP plugin! one thing, in the drop down menu we see an error. wondering if we need to be concerned. It states: 

/Users/ME/BitBar_PluginsFolder/netstats.5s.sh: line 72: [: : integer expression expected

what do you think?

**Comment by sprak3000** [comment]
This appears to have been addressed in a previous PR.
