### ISSUE TITLE
re: Now playing

### ISSUE THREAD

**Issue by stefan1983** [matryer/xbar-plugins#1178]
FAO: (@adampk90)

Can you please add support for IINA? 

Thanks

**Comment by sprak3000** [comment]
@stefan1983 

If you edit the plugin, you could try adding IINA to the list of apps:

```
apps=(Music Spotify Vox)
```

becomes

```
apps=(Music Spotify Vox IINA)
```

I've never used that particular player, so I do not know for sure if it works with the script.
