### ISSUE TITLE
re: Spotify Now Playing (via spotctl)

### ISSUE THREAD

**Issue by keithah** [matryer/xbar-plugins#1197]
FAO: (@Igor1201)

<img width="901" alt="image" src="https://user-images.githubusercontent.com/684920/54047015-c8b35900-418a-11e9-9273-ee75560ebcfe.png">

Seeing these errors when I use the script, but looks like it works still?

**Comment by Igor1201** [comment]
Hmm, weird. You're probably using a new bash version which changed the way substitution works. But this regex can be simplified anyway.

**Comment by Igor1201** [comment]
☝️ just opened a PR to fix it

**Comment by sprak3000** [comment]
Looks like the fix was merged in awhile ago. Closing.
