### ISSUE TITLE
pull request failed, what should I do then?

### ISSUE THREAD

**Issue by nnnggel** [matryer/xbar-plugins#1202]
https://github.com/matryer/bitbar-plugins/pull/1201

**Comment by warmup72** [comment]
My PullRequest also fails ---- same question - What todo?!?
https://github.com/matryer/bitbar-plugins/pull/1203

**Comment by Dispader** [comment]
@nnnggel @warmup72 I managed to fix the Ruby dependencies for CI in Pull Request #1200 by updating the version of Ruby the build sets up with `rvm`.

```yaml
before_install:
  - rvm install 2.2.10
  - rvm use 2.2.10
```

In my case, I chose to isolate the CI build fix to commit 7ccfac7a44f7c06a4cdf0b70eb1f455d8fd31ff4 .

**Comment by warmup72** [comment]
Thanks for Your answer, but i didn´t know what to do now?
Can You please explain it for someone new on github?

**Comment by nnnggel** [comment]
> @nnnggel @warmup72 I managed to fix the Ruby dependencies for CI in Pull Request #1200 by updating the version of Ruby the build sets up with `rvm`.
> 
> ```yaml
> before_install:
>   - rvm install 2.2.10
>   - rvm use 2.2.10
> ```
> 
> In my case, I chose to isolate the CI build fix to commit [7ccfac7](https://github.com/matryer/bitbar-plugins/commit/7ccfac7a44f7c06a4cdf0b70eb1f455d8fd31ff4) .

thx,I'll try it later.

**Comment by nnnggel** [comment]
> @nnnggel @warmup72 I managed to fix the Ruby dependencies for CI in Pull Request #1200 by updating the version of Ruby the build sets up with `rvm`.
> 
> ```yaml
> before_install:
>   - rvm install 2.2.10
>   - rvm use 2.2.10
> ```
> 
> In my case, I chose to isolate the CI build fix to commit [7ccfac7](https://github.com/matryer/bitbar-plugins/commit/7ccfac7a44f7c06a4cdf0b70eb1f455d8fd31ff4) .

It works!
https://github.com/matryer/bitbar-plugins/pull/1212

**Comment by nnnggel** [comment]
> Thanks for Your answer, but i didn´t know what to do now?
> Can You please explain it for someone new on github?

1. update(fetch/pull/merge) your forked repo from https://github.com/matryer/bitbar-plugins
2. push the updated code from local (your pc) to your origin repo
3. travis will auto make/build again

**Comment by warmup72** [comment]
Hi thanks for your answer, i´ve tried it, but I get another Error 1203 :-(
https://travis-ci.org/matryer/bitbar-plugins/builds/515830160?utm_source=github_status&utm_medium=notification

**Comment by Dispader** [comment]
Nine days ago, Pull #1206 got merged, so many of the problems with `.travis.yml` y'may have seen can be fixed by a `git rebase upstream/master`.
