### ISSUE TITLE
re: Product Hunt - Today in Tech

### ISSUE THREAD

**Issue by htirma** [matryer/xbar-plugins#1228]
FAO: (@flesch)
Hey there!
I'm Amrith from the Product Hunt team :)
We're upgrading our APIs from scratch with a lot of added improvements and are eventually gonna deprecate the V1 API.
Let me know if you'd like early access to the new API! I'm at amrith@producthunt.com :)
Best,
Amrith

**Comment by sprak3000** [comment]
@shnbhg 

I just tried this plugin, and it still seems to work. Was your V1 API ever deprecated?
