### ISSUE TITLE
re: Github review requests

### ISSUE THREAD

**Issue by nicolas-g** [matryer/xbar-plugins#1286]
FAO: (@bogdal)

Hi, I'm having issues to see actual Pull Requests with this plugin, I followed the [instructions](https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line) in order to create an access token and even gave the token full access but any attempt to run the script it always returns #0 .

Can you please advise ? Also if someone can also tell me the exact minimum permissions I need to just give access for the plugin to work that will be great.

PS: I'm part of a Github organization and there are currently some PR assigned to me.

**Comment by sprak3000** [comment]
@nicolas-g 

Did you ever get this issue resolved?

**Comment by nicolas-g** [comment]
I haven't tried since then but you can close this issue as I'm not planning to use the plugin anymore.
