### ISSUE TITLE
re: Real CPU Usage Chart (▁▃▃█▇▃)

### ISSUE THREAD

**Issue by DaWy** [matryer/xbar-plugins#1333]
FAO: (@maio)

Well, i'm using a Gnome Shell extension on Ubuntu 19.10 to make Bitbar plugins work on Gnome Shell at menu bar.

Is working great except for those plugins like the CPU Usage Chart, that use other commands to get the CPU usage.

I've modified the plugin to make it compatible with almost any linux distro using iotop instead of top. As I don't have any MAC and I don't know how to check current running version on MAC OS, i'm just throwing the code here and hopes help someone to make this plugin code working on MACOS/Linux distro.

I've just modified the CURRENT and IDLE content. Hope that helps!

```
IDLE=$(iostat -c 1 2 | tail -n4 | grep ',' | cut -c51-55)
CURRENT=$(echo "100 - $IDLE" | sed -r 's/[,]+/./g' | bc | cut -c1-3)
```

**Comment by tresni** [comment]
Using `iostat -c 1 2` on OSX causes it to loop every 2 seconds.  Need to use `disk2` instead of `2` if you want to look at the second disk.

**Comment by sprak3000** [comment]
Closing due to age.
