### ISSUE TITLE
re: Stock Ticker

### ISSUE THREAD

**Issue by mattcaunt** [matryer/xbar-plugins#1400]
FAO: (@rkanter)
Enjoying the Stock Ticker Bitbar plugin for OS X but looking for some advise as running out of API messages on IEX Cloud within a few days when monitoring several stocks.

Is there a better free account to IEX or a way to alter the codes stock lookup interval / trading hour threshold?

Thanks
Matt

**Comment by tresni** [comment]
If you change the filename it won't be run as frequently.  stock-ticker.30s.py runs it every 30 seconds.  Change it to stock-ticker.5m.py to run it every 5 minutes (for example.)

**Comment by mattcaunt** [comment]
Thanks :)

**Comment by mattcaunt** [comment]
Anyone able to modify the coding to only perform stock lookups within trading hours?

This would save on the API message calls... just out of interest.
