### ISSUE TITLE
spotify.10s.sh pulling data sometimes with Spotify 1.1.31.703.g256add22

### ISSUE THREAD

**Issue by jajajaime** [matryer/xbar-plugins#1424]
This morning I updated to the latest Spotify app version 1.1.31.703.g256add22 on macOS Catalina 10.15.3. That rendered the spotify.10s.sh plugin to display the song info sometimes.
Sometimes it pulls it for a song, and 10s later it is gone, although the album info always gets pulled.

This is it without the info now
![image](https://user-images.githubusercontent.com/13631233/80134194-3c612280-8553-11ea-9256-21771247f8f3.png)

I tried restarting Spotify, and Bitbar, to no avail.

**Comment by jajajaime** [comment]
And here's an example of the same song playing, but that it got pulled and then not 10s later.
![image](https://user-images.githubusercontent.com/13631233/80134308-6e728480-8553-11ea-9f8e-db0336566660.png)
![image](https://user-images.githubusercontent.com/13631233/80134365-85b17200-8553-11ea-9372-7b188dd84313.png)

**Comment by jajajaime** [comment]
Installing an older version fixes the issue, but Spotify likes to auto update whenever the app launches, so I guess I need to wait for a new version of Spotify so that they fix their song reporting.

**Comment by sprak3000** [comment]
@jajajaime 

Has this issue reappeared since you last commented? Is this something the plugin still needs to address?

**Comment by jajajaime** [comment]
@sprak3000 I do not use Spotify any longer, so not sure if it happens or not.
