### ISSUE TITLE
re: Currency Tracker Transferwise

### ISSUE THREAD

**Issue by fiorins** [matryer/xbar-plugins#1434]
FAO: (@andrewzk) i have this error, i don't know why 
<img width="1280" alt="Screenshot 2020-04-30 19 18 54" src="https://user-images.githubusercontent.com/32281481/80740046-c1ca7100-8b17-11ea-9203-af6dc07156ea.png">

**Comment by sprak3000** [comment]
No response from author in over two years. Closing.
