### ISSUE TITLE
Request: Homebridge UI Plugin

### ISSUE THREAD

**Issue by C4Wiz** [matryer/xbar-plugins#1509]
anyone use Homebridge UI?
[https://github.com/oznu/homebridge-config-ui-x](url)

api here:
[https://github.com/oznu/homebridge-config-ui-x/wiki/API-Reference](url)

i would be willing to donate if someone is willing to write the plugin

**Comment by EricAndrechek** [comment]
Ok @C4Wiz, I am a developer for homebridge and I'd be willing to write a plugin for you, what sort of things would you like it to accomplish?

**Comment by C4Wiz** [comment]
> Ok @C4Wiz, I am a developer for homebridge and I'd be willing to write a plugin for you, what sort of things would you like it to accomplish?

@EricAndrechek, thank you so much. i would like the ability to see current versions, upsates available, status, restart homebridge

**Comment by EricAndrechek** [comment]
Hey, @C4Wiz I created a [pull request](https://github.com/matryer/bitbar-plugins/pull/1526) for the homebridge plugin, I think it does just about everything you asked for. 

Here is a preview: 
![image](https://user-images.githubusercontent.com/35144594/102293908-0b849200-3f16-11eb-9778-7ce25edcc7ec.png)

You should be able to download it from the PR even before/if it gets accepted as a merge. I don't know if your original offer of a donation still stands, but if it does I would appreciate it! [Here is my PayPal link](https://www.paypal.com/donate/?token=vMzClqbU7oBI5-rit0h8QZBaRnEMJ6kUrhbvKzCo6Ur4ye6wiF_yXyu3aS1fKcktBJBrPOSUlWPy2Wgo&fromUL=true), took me about 3 hours to get working and ironed out. Let me know if you'd like any changes or added features.

**Comment by C4Wiz** [comment]
> Hey, @C4Wiz I created a [pull request](https://github.com/matryer/bitbar-plugins/pull/1526) for the homebridge plugin, I think it does just about everything you asked for.
> 
> Here is a preview:
> ![image](https://user-images.githubusercontent.com/35144594/102293908-0b849200-3f16-11eb-9778-7ce25edcc7ec.png)
> 
> You should be able to download it from the PR even before/if it gets accepted as a merge. I don't know if your original offer of a donation still stands, but if it does I would appreciate it! [Here is my PayPal link](https://www.paypal.com/donate/?token=vMzClqbU7oBI5-rit0h8QZBaRnEMJ6kUrhbvKzCo6Ur4ye6wiF_yXyu3aS1fKcktBJBrPOSUlWPy2Wgo&fromUL=true), took me about 3 hours to get working and ironed out. Let me know if you'd like any changes or added features.

thank you so much, i did not recieve a notification on this post, sorry for the late reply. i will test it today

**Comment by C4Wiz** [comment]
i am getting this error:
<img width="589" alt="Screen Shot 2021-01-03 at 9 01 44 AM" src="https://user-images.githubusercontent.com/3883521/103480444-69342d80-4da2-11eb-998c-4230b70e022b.png">

**Comment by EricAndrechek** [comment]
Ok, that's an easy fix, can you open Terminal on your Mac and type `pip3 install requests`? If it tells you `pip3 cannot be found` try just running `pip install requests`.

**Comment by C4Wiz** [comment]
> Ok, that's an easy fix, can you open Terminal on your Mac and type `pip3 install requests`? If it tells you `pip3 cannot be found` try just running `pip install requests`.

Yep ran that already, still get the error

**Comment by EricAndrechek** [comment]
Ok, after some further investigation I found that this appears to be very similar to [this issue](https://github.com/matryer/bitbar-plugins/issues/1015). What happens when you type `which python` in terminal?

**Comment by C4Wiz** [comment]
> Ok, after some further investigation I found that this appears to be very similar to [this issue](https://github.com/matryer/bitbar-plugins/issues/1015). What happens when you type `which python` in terminal?

`/Users/Dave/.pyenv/shims/python`

**Comment by EricAndrechek** [comment]
Ok, try changing line one in the code where it currently says `#!/usr/bin/env PYTHONIOENCODING=UTF-8 python3` to instead say:
```python
#!//Users/Dave/.pyenv/shims/python 
#encoding: utf-8
```

(or change the "python" to "python3" if you'd prefer that)

**Comment by C4Wiz** [comment]
> Ok, try changing line one in the code where it currently says `#!/usr/bin/env PYTHONIOENCODING=UTF-8 python3` to instead say:
> 
> ```python
> #!//Users/Dave/.pyenv/shims/python 
> #encoding: utf-8
> ```
> 
> (or change the "python" to "python3" if you'd prefer that)

<img width="589" alt="Screen Shot 2021-01-03 at 9 01 44 AM" src="https://user-images.githubusercontent.com/3883521/103491854-fc964e80-4df4-11eb-8515-baf1f33cc3c9.png">

**Comment by C4Wiz** [comment]
i installed the plugin from the issue you posted above and it returns this:

<img width="693" alt="Screen Shot 2021-01-03 at 6 53 02 PM" src="https://user-images.githubusercontent.com/3883521/103491939-8cd49380-4df5-11eb-94e0-b474f4385c20.png">

**Comment by C4Wiz** [comment]
in terminal if i type:
`python -V`
`Python 3.8.5`

**Comment by EricAndrechek** [comment]
Aha, that seems to be it then, your pip and python installations are running version 3 from the terminal but version 2 from bitbar. What is the result of running `whereis python3` and `whereis python`? Hopefully if we can find the correct python path we can change the location the bitbar plugins runs it from to be the correct one. Also, take a look at [this webpage](https://scmquest.com/resolved-importerror-no-module-named-requests-usr-bin-python-no-module-named-pip-on-macos/) to see that requests is indeed installed. You can also try installing requests module onto your python 2.7 installation by running `/usr/bin/python -m pip install --user requests`

If none of that works, I can try a hacky workaround to just avoid using the requests module.

**Comment by C4Wiz** [comment]
```
>>> help("modules")

Please wait a moment while I gather a list of all available modules...

__future__          _threading_local    getpass             runpy
_abc                _tracemalloc        gettext             sched
_ast                _uuid               glob                secrets
_asyncio            _warnings           grp                 select
_bisect             _weakref            gzip                selectors
_blake2             _weakrefset         hashlib             setuptools
_bootlocale         _xxsubinterpreters  heapq               shelve
_bz2                _xxtestfuzz         hmac                shlex
_codecs             abc                 html                shutil
_codecs_cn          aifc                http                signal
_codecs_hk          antigravity         idlelib             site
_codecs_iso2022     argparse            idna                smtpd
_codecs_jp          array               imaplib             smtplib
_codecs_kr          ast                 imghdr              sndhdr
_codecs_tw          asynchat            imp                 socket
_collections        asyncio             importlib           socketserver
_collections_abc    asyncore            inspect             sqlite3
_compat_pickle      atexit              io                  sre_compile
_compression        audioop             ipaddress           sre_constants
_contextvars        base64              itertools           sre_parse
_crypt              bdb                 json                ssl
_csv                binascii            keyword             stat
_ctypes             binhex              lib2to3             statistics
_ctypes_test        bisect              linecache           string
_curses             builtins            locale              stringprep
_curses_panel       bz2                 logging             struct
_datetime           cProfile            lzma                subprocess
_dbm                calendar            mailbox             sunau
_decimal            certifi             mailcap             symbol
_dummy_thread       cgi                 marshal             symtable
_elementtree        cgitb               math                sys
_functools          chardet             mimetypes           sysconfig
_hashlib            chunk               mmap                syslog
_heapq              cmath               modulefinder        tabnanny
_imp                cmd                 multiprocessing     tarfile
_io                 code                netrc               telnetlib
_json               codecs              nis                 tempfile
_locale             codeop              nntplib             termios
_lsprof             collections         ntpath              test
_markupbase         colorsys            nturl2path          textwrap
_md5                compileall          numbers             this
_multibytecodec     concurrent          opcode              threading
_multiprocessing    configparser        operator            time
_opcode             contextlib          optparse            timeit
_operator           contextvars         os                  tkinter
_osx_support        copy                parser              token
_pickle             copyreg             pathlib             tokenize
_posixshmem         crypt               pdb                 trace
_posixsubprocess    csv                 pickle              traceback
_py_abc             ctypes              pickletools         tracemalloc
_pydecimal          curses              pip                 tty
_pyio               dataclasses         pipes               turtle
_queue              datetime            pkg_resources       turtledemo
_random             dbm                 pkgutil             types
_scproxy            decimal             platform            typing
_sha1               difflib             plistlib            unicodedata
_sha256             dis                 poplib              unittest
_sha3               distutils           posix               urllib
_sha512             doctest             posixpath           urllib3
_signal             dummy_threading     pprint              uu
_sitebuiltins       easy_install        profile             uuid
_socket             email               pstats              venv
_sqlite3            encodings           pty                 warnings
_sre                ensurepip           pwd                 wave
_ssl                enum                py_compile          weakref
_stat               errno               pyclbr              webbrowser
_statistics         faulthandler        pydoc               wsgiref
_string             fcntl               pydoc_data          xdrlib
_strptime           filecmp             pyexpat             xml
_struct             fileinput           queue               xmlrpc
_symtable           fnmatch             quopri              xxlimited
_sysconfigdata__darwin_darwin formatter           random              xxsubtype
_testbuffer         fractions           re                  zipapp
_testcapi           ftplib              readline            zipfile
_testimportmultiple functools           reprlib             zipimport
_testinternalcapi   gc                  requests            zlib
_testmultiphase     genericpath         resource            
_thread             getopt              rlcompleter         

Enter any module name to get more help.  Or, type "modules spam" to search
for modules whose name or summary contain the string "spam".
```

**Comment by C4Wiz** [comment]
> Aha, that seems to be it then, your pip and python installations are running version 3 from the terminal but version 2 from bitbar. What is the result of running `whereis python3` and `whereis python`? Hopefully if we can find the correct python path we can change the location the bitbar plugins runs it from to be the correct one. Also, take a look at [this webpage](https://scmquest.com/resolved-importerror-no-module-named-requests-usr-bin-python-no-module-named-pip-on-macos/) to see that requests is indeed installed. You can also try installing requests module onto your python 2.7 installation by running `/usr/bin/python -m pip install --user requests`
> 
> If none of that works, I can try a hacky workaround to just avoid using the requests module.

```
 whereis python3
/usr/bin/python3
```

```
whereis python
/usr/bin/python

```

**Comment by EricAndrechek** [comment]
Ok, fingers crossed this works, try changing those first few lines then to say
```python
#!/usr/bin/python3
#encoding: utf-8
```

Python3 seems to work on your computer, and it looks like requests is indeed installed so hopefully this gets bitbar to use the correct version.

**Comment by C4Wiz** [comment]
nope same error

**Comment by EricAndrechek** [comment]
Oh man, I just realized I missed the message where you mentioned the error changed to saying "Couldn't posix_spawn: error 8" my bad!

If you haven't done so already, would you mind trying to make this file executable by running `sudo chmod +x /path/to/homebridge.3s.py`

Also, try opening terminal and running `python /path/to/homebridge.3s.py` and let me know what it outputs.

**Comment by EricAndrechek** [comment]
You can also try something other users have mentioned worked but I couldn't get to run on my machine, try running `xattr -d com.apple.quarantine /path/to/homebridge.3s.py` to make sure your computer knows it is safe to run.

**Comment by C4Wiz** [comment]
> Also, try opening terminal and running `python /path/to/homebridge.3s.py` and let me know what it outputs.

```
python /Users/Dave/Documents/bitbar\ plugins/homebridge.10s.py 
Traceback (most recent call last):
  File "/Users/Dave/Documents/bitbar plugins/homebridge.10s.py", line 154, in <module>
    config.touch(exist_ok=True)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/pathlib.py", line 1277, in touch
    fd = self._raw_open(flags, mode)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/pathlib.py", line 1086, in _raw_open
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/Dave/.config/bitbar/config'
```

**Comment by EricAndrechek** [comment]
Can you create a folder called `.config` in your home directory, then make a `bitbar` folder within that? That's the default location for bitbar plugins so it is set to adjust the configuration there.

**Comment by C4Wiz** [comment]
ok i added the folders, and i also changed the top of the file to:

```
#!/Users/Dave/.pyenv/versions/3.8.5/bin/python
#encoding: utf-8
```

now there is a red X in bitbar

**Comment by C4Wiz** [comment]
ok, i added my username and pass to the config file and:
<img width="263" alt="Screen Shot 2021-01-04 at 8 44 45 AM" src="https://user-images.githubusercontent.com/3883521/103541244-2b4e0c80-4e69-11eb-97a3-012108566873.png">

**Comment by EricAndrechek** [comment]
Great! I was just typing out how to go in and do that but you got it figured out! Are all those fields good or did you want any other data to show up there? Also if you see the "icon" field in the config you can change which thing you want to show in the menu bar instead of the green checkmark.

**Comment by C4Wiz** [comment]
perhaps a link at the top of the dropdown to open the gui
a submenu to trigger favorites
convert C to F
display current version of plugins
add restart server

**Comment by C4Wiz** [comment]
perhaps use the homebridge official icon for status up and a red version for down

**Comment by C4Wiz** [comment]
node version and update available

**Comment by EricAndrechek** [comment]
Ok, I will get working on all of those things and get back to you when they are working. It looks like a hard server restart is only available if your server is Linux, so I'll add that but it may not be functional if you are not running homebridge on a Linux server.

**Comment by C4Wiz** [comment]
> Ok, I will get working on all of those things and get back to you when they are working. It looks like a hard server restart is only available if your server is Linux, so I'll add that but it may not be functional if you are not running homebridge on a Linux server.

thank you sir!

i am running the official Raspberry PI Image on a Pi2B

**Comment by EricAndrechek** [comment]
Alright, done the changes you requested except for the "submenu to trigger favorites" as I wasn't quite sure what you meant by that. Anyway, the other changes have all been updated in my [pull request](https://github.com/matryer/bitbar-plugins/pull/1526), be sure to leave the top 2 lines as the ones that worked for you, and you will also need to add a line to your config file that should say `unit = "C"` or `unit = "F"`. Sorry it took so long, I had some issues getting the icon to look right in the menu bar, but it should all be working now.

**Comment by C4Wiz** [comment]
looks great!

just maybe remove the version number after up to date, seems redundant since it's the same as current

**Comment by EricAndrechek** [comment]
Done, didn't even think about that, good call.

**Comment by C4Wiz** [comment]
much better.

i seperated the Homebridge is up from the link to open the ui, more intuitive i think

```
        printer('---')
        print ('Open Homebridge UI | href=' + url)
        printer('---')
        printer(status)
```

<img width="343" alt="Screen Shot 2021-01-05 at 11 08 20 AM" src="https://user-images.githubusercontent.com/3883521/103669455-5b1f1200-4f46-11eb-8f80-95ef68fdea84.png">

**Comment by C4Wiz** [comment]
any way to make the new update clickable to launch the terminal and run the updater?

**Comment by EricAndrechek** [comment]
I think I will separate the UI like that, and I also don't think there is a way for me to make it update automatically, but I can maybe have it bring you to the plugins page or something to let you quickly click update?

**Comment by EricAndrechek** [comment]
Alright, I pushed a new update with some of those features you mentioned, along with an automated dark/light mode switcher to make sure it looks correct regardless of what theme you have. Let me know if there is anything else to add!

**Comment by C4Wiz** [comment]
great idea on the dark/light mode detection.

i have a question on the RAM %, is it used or free? mine shows 64% but in the ui it shows this:

<img width="384" alt="Screen Shot 2021-01-05 at 4 33 58 PM" src="https://user-images.githubusercontent.com/3883521/103701539-2f1a8580-4f74-11eb-91ca-fdf1def14ef2.png">

**Comment by C4Wiz** [comment]
maybe add the current version and updates for homebridge itself

**Comment by C4Wiz** [comment]
also i am showing 1 update available even though it says all are up to date:

<img width="317" alt="Screen Shot 2021-01-05 at 4 47 18 PM" src="https://user-images.githubusercontent.com/3883521/103703602-cfbd7500-4f75-11eb-9821-95ea21562710.png">

**Comment by EricAndrechek** [comment]
> maybe add the current version and updates for homebridge itself

Done.

> also i am showing 1 update available even though it says all are up to date

Fixed. Silly mistake on my part, good catch.

> i have a question on the RAM %, is it used or free? mine shows 64% but in the ui it shows this

I looked into RAM and it is coming in flawed from Homebridge's side. I mentioned it to some other devs and escalated the issue with them. Hopefully, that can be patched shortly.

**Comment by EricAndrechek** [comment]
Ok, I have worked out and determined the issue with RAM, and Homebridge has decided it is "not worth fussing over", so I rolled out a patch in my own code and have patched it for this plugin. Basically, Homebridge inaccurately reports values in GB instead of GiB, so the values were slightly messed up. Now RAM should accurately show % used.

**Comment by C4Wiz** [comment]
this is fantastic work! Looks awesome, and you sir are top notch.

do you see on your side that the nodejs and homebridge info seems to be in bold and the other plugins are not?

<img width="324" alt="Screen Shot 2021-01-06 at 8 01 32 AM" src="https://user-images.githubusercontent.com/3883521/103771276-6b41fa80-4ff5-11eb-9d1f-315a4ce34bdf.png">

**Comment by EricAndrechek** [comment]
Thanks. I do see that, it is because all the other plugins are links to their plugin homepage whereas NodeJS and Homebridge do not. Do you want me to remove all the links entirely or have NodeJS and Homebridge link back to their homepages?

**Comment by C4Wiz** [comment]
link back to release notes page for all sounds good

**Comment by C4Wiz** [comment]
also would it be possible to put a option in the config to replace up/down for homebridge status with user defined wording?

IE: Homebridge is Active/inActive Online/Offline

**Comment by EricAndrechek** [comment]
Plugins all link to release pages now, and on line [164 & 165](https://github.com/matryer/bitbar-plugins/blob/9ac5f50afcaf0d663ddb780c0560ec1e4f64e733/IOT/homebridge.10s.py#L164-L165) you can change what word you want it to say for you.

**Comment by C4Wiz** [comment]
Awesome work!

**Comment by EricAndrechek** [comment]
Thanks! I don't know if your original offer still stands, but I have spent a fair amount of time on this, so [here is my Paypal ](https://www.paypal.com/donate/?token=vMzClqbU7oBI5-rit0h8QZBaRnEMJ6kUrhbvKzCo6Ur4ye6wiF_yXyu3aS1fKcktBJBrPOSUlWPy2Wgo&fromUL=true) if you would be so generous. I have spent a good number of hours working on this plugin, and could really use the money. If not no hard feelings either.

**Comment by C4Wiz** [comment]
> Thanks! I don't know if your original offer still stands, but I have spent a fair amount of time on this, so [here is my Paypal ](https://www.paypal.com/donate/?token=vMzClqbU7oBI5-rit0h8QZBaRnEMJ6kUrhbvKzCo6Ur4ye6wiF_yXyu3aS1fKcktBJBrPOSUlWPy2Wgo&fromUL=true) if you would be so generous. I have spent a good number of hours working on this plugin, and could really use the money. If not no hard feelings either. 

![image](https://user-images.githubusercontent.com/3883521/103920721-3d34e700-50d7-11eb-8d1f-8c2705b18f70.png)

**Comment by EricAndrechek** [comment]
Weird that it didn't work, I made a new link hopefully [this link](https://paypal.me/andrechekeric) will work. Thank you!

**Comment by JannikArndt** [comment]
Hey @EricAndrechek! Great plugin, thank you 🙏 
This issue helped me getting it to work, I want to share what I had to do with you, to make it easier to automate these steps (or for others to follow them):

1. after installing `xbar` and this plugin as the very first (via [this](https://xbarapp.com/docs/plugins/IoT/homebridge.10s.py.html)), the menu bar showed

<img width="437" alt="image" src="https://user-images.githubusercontent.com/7119122/112029034-1bc19400-8b39-11eb-88fc-b4cea56a1d30.png">

I ran `pip3 install requests` successfully, but that didn't help, `python3 -m pip install --user requests` is what did the trick (I'll never understand python, as a jvm dev 😅).

2. since this is my first plugin, I didn't have a config file yet:
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/7119122/112029336-6d6a1e80-8b39-11eb-8ff1-5d81af57f334.png">

No problem, but nothing besides the error message ever told me to create one. That's a low-hanging UX fruit 😛 

3. This one needs some stupidity to run into: I added the user and password, but not the hostname 🤦 (since an example value was already filled in). The "nodename nor servername provided" tipped me off:
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/7119122/112029595-b621d780-8b39-11eb-8cc9-56125b83b494.png">

--------

After that, it worked perfectly, thank you again!

<img width="397" alt="image" src="https://user-images.githubusercontent.com/7119122/112030039-1fa1e600-8b3a-11eb-8497-2f49c8a2d315.png">

**Comment by EricAndrechek** [comment]
@JannikArndt Glad to hear things are working for you with the plugin. I originally developed it for BitBar (before the migration to what is now xbar) and so a few things, like the config files, are slightly different, so the original functionality of a helpful and easier to setup configuration wizard must have broken. When u get a chance hopefully I'll be able to migrate the plugin to use new Xbar features, but since I am no longer running MacOS it is harder for me to test.

**Comment by matryer** [comment]
@EricAndrechek this is pretty cool, good work. Would love to see it refreshed for xbar, but it should still work either way. Is this plugin in the repo?

**Comment by C4Wiz** [comment]
@EricAndrechek i would be glad to test the changes for you!

any chance you can move the upWord, downWord to the config file. it is easier for users to edit the config file as opposed to the script itself

**Comment by matryer** [comment]
Or better still, if the new Variables feature would help?

https://xbarapp.com/docs/2021/03/14/variables-in-xbar.html

**Comment by C4Wiz** [comment]
ok, i have moved the upword, down word to the config file:

here are the changes i made:

`                state = True
            status = "Homebridge is " + upword if state else downword`

`def login(username, password, url, icon, command, unit, config, upword, downword):`

`        with open(config, 'w') as newConfig:
            newConfig.write(firstSection)
            newConfig.write('[homebridge]\n')
            newConfig.write("# edit the username and password to your homebridge's and then save and close\n")
            newConfig.write("# you can also modify the url from the default if desired\n")
            newConfig.write("# to change the icon image, specify whether you want to see: \"CPU\", \"TEMP\", \"RAM\", \"UPTIME\", \"UPDATES\", or \"STATUS\". Defaults to \"STATUS\"\n")
            newConfig.write("username = \"{}\"\n".format(username))
            newConfig.write("password = \"{}\"\n".format(password))
            newConfig.write("url = \"{}\"\n".format(url))
            newConfig.write("icon = \"{}\"\n".format(icon))
            newConfig.write("token = \"{}\"\n".format(token))
            newConfig.write("unit = \"{}\"\n".format(unit))
            newConfig.write("upword = \"{}\"\n".format(upword))
            newConfig.write("downword = \"{}\"\n".format(downword))
            newConfig.write(lastSection)`

`if hbConfig == []:
    with open(config, "a") as file:
        file.write("\n[homebridge]\n")
        file.write("# edit the username and password to your homebridge's and then save and close\n")
        file.write("# you can also modify the url from the default if desired\n")
        file.write("# to change the icon image, specify whether you want to see: \"CPU\", \"TEMP\", \"RAM\", \"UPTIME\", \"UPDATES\", or \"STATUS\". Defaults to \"STATUS\"\n")
        file.write("username = \"\"\n")
        file.write("password = \"\"\n")
        file.write("url = \"http://homebridge.local\"\n")
        file.write("icon = \"STATUS\"\n")
        file.write("token = \"\"\n")
        file.write("unit = \"F\"\n")
        file.write("upword = \"Online\"\n")
        file.write("downword = \"Offline\"\n")`

`else:
    token = ""
    username = ""
    password = ""
    url = ""
    icon = ""
    unit = ""
    upword = ""
    downword = ""
    for line in hbConfig:
        if line.split(" = ")[0] == "username":
            username = line.split(" = ")[1].split("\"")[1]
        elif line.split(" = ")[0] == "password":
            password = line.split(" = ")[1].split("\"")[1]
        elif line.split(" = ")[0] == "token":
            token = line.split(" = ")[1].split("\"")[1]
        elif line.split(" = ")[0] == "url":
            url = line.split(" = ")[1].split("\"")[1]
        elif line.split(" = ")[0] == "icon":
            icon = line.split(" = ")[1].split("\"")[1]
        elif line.split(" = ")[0] == "unit":
            unit = line.split(" = ")[1].split("\"")[1]
        elif line.split(" = ")[0] == "upword":
            upword = line.split(" = ")[1].split("\"")[1]
        elif line.split(" = ")[0] == "downword":
            downword = line.split(" = ")[1].split("\"")[1]`

`        if checkToken.status_code == 401:
            login(username, password, url, icon, command, unit, upword, downword, config)`

`    else:
        login(username, password, url, icon, command, unit, upword, downword, config)`

**Comment by EricAndrechek** [comment]
Hi, @C4Wiz and @matryer thanks for the kind words! I will take a look at the code @C4Wiz has added here and work on making a pull request to update the current plugin. I'll let you guys know when it is ready to be tested.
