### ISSUE TITLE
Get gateway NIC instead of presuming it to be en0 in bitbar-plugins/netstats.5s.sh

### ISSUE THREAD

**Issue by hoondi** [matryer/xbar-plugins#1512]
in netstats.5s.sh

add following at Line 31:
`CURRENT_GATEWAY=$(route -n get default | grep -o "interface: .*" | sed -e 's/interface: //')`

update following line to reference above:
`LOCAL_IP=$(ipconfig getifaddr $CURRENT_GATEWAY 2>&1)`

This removed the red ❌ from my menubar and all is working now.

**Comment by Joshfindit** [comment]
@hoondi If you're still interested, can you try https://github.com/Joshfindit/xbar-plugins/blob/patch-2/Network/netstats.5s.sh ?

It exposes the interface as a variable, and uses your code to get the default if it's not specified
