### ISSUE TITLE
bitbar text off center in newest mac os update

### ISSUE THREAD

**Issue by squashmcdermott** [matryer/xbar-plugins#1515]
See image, the trashcan 9.0G one is a bitbar app, it is way higher than all other menubar items. any idea how to fix? 

<img width="339" alt="Screenshot 2020-11-13 at 16 49 55" src="https://user-images.githubusercontent.com/10843616/99034017-58e8a900-25d0-11eb-82fb-b73627fcfe27.png">

**Comment by idoo** [comment]
Fixed here https://github.com/matryer/bitbar/issues/583
