### ISSUE TITLE
“BitBar.app” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by dmytrob** [matryer/xbar-plugins#1527]
Hi, when I am trying to open BitBar app installed by brew tool I get message 
```
“BitBar.app” can’t be opened because Apple cannot check it for malicious software.
This software needs to be updated. Contact the developer for more information.
Chrome downloaded this file yesterday at 22:10 from github.com.
```
Opening the app with Control+RMB-> Open or clicking button "Open Anyway" in Security&Privacy give the same result.

My System is: 
MacOs BigSur version 11.1
MacBook Pro (16-inch, 2019)

Is there any other workarounds for that? Or could you maybe sign the package?

Thanks.

**Comment by bhusang** [comment]
There is a way to install the program. But it is risky per Apple -- use control + mouse click on the app - or google how to install unsigned software (e.g. https://www.macworld.co.uk/how-to/mac-app-unidentified-developer-3669596/).

**Comment by matryer** [comment]
Thanks @dmytrob - we will fix this when we properly sign the xbar app when it's out of beta.
