### ISSUE TITLE
Notice: All <bitbar...></bitbar...> metadata will be replaced with `xbar`

### ISSUE THREAD

**Issue by matryer** [matryer/xbar-plugins#1563]
xbar is the replacement of BitBar, and since the repo name changed, the metadata in the plugins will be changed for consistency.

I will do this in one commit some point this week. Please update any tooling that relies on the old metadata format.

* Old `bitbar` metadata will continue to work for the time being
* Notice xbar introduces variables, which may be suitable for a lot of plugins

**Comment by mrusme** [comment]
Ah, now this is probably what's causing [my confusion](https://github.com/matryer/xbar-plugins/pull/1568#issuecomment-802105769). Alright, I'll just wait it out until the CI was updated as well. :)
