### ISSUE TITLE
001-doge-usd.py: no JSON object could be decoded

### ISSUE THREAD

**Issue by xe-nvdk** [matryer/xbar-plugins#1601]
<img width="798" alt="Screen Shot 2021-04-16 at 11 51 00 AM" src="https://user-images.githubusercontent.com/64545348/115042587-062a5a80-9eaa-11eb-8242-a1bb6e85dafc.png">
fao @impshum -

**Comment by impshum** [comment]
Use python 3+.

**Comment by xe-nvdk** [comment]
I'm already using python3 🤷‍♂️

**Comment by impshum** [comment]
I've updated the tickers.

https://github.com/matryer/xbar-plugins/pull/1606/files
