### ISSUE TITLE
002-gitlab_merge_requests.js: 

### ISSUE THREAD

**Issue by andreicorpo** [matryer/xbar-plugins#1607]
fao @simeonc - Hi. I just can't get this to work. I have set my token but all I see is the gitlab logo.

**Comment by SimeonC** [comment]
Hey, didn't know about this new repo!!

If you're seeing just the gitlab icon I think you don't have any MRs you have opened (ie author) or are assigned to you. (I haven't updated it to work with the new reviewers API yet)

It'll also have an icon when you push a new branch (today only, filters out previous days)

If it has an error it'll show that in the drop down.

**Comment by andreicorpo** [comment]
I don't have any errors, but I do have opened MRs and assigned MRs. 🤔

**Comment by SimeonC** [comment]
Hmmmm, what permissions did you give your token? It might be that. I can check this script is up to date on Monday as it's working on my local machine - though under the old bitbar, not that that should make a difference I don't think.

**Comment by andreicorpo** [comment]
Initially I gave it `api` permissions. After that - seeing that is not working - I gave it all the permissions except the write ones.

**Comment by SimeonC** [comment]
Hmm, OK. I'll check the script on Monday as it's working on my work machine. I probably bug fixed it and forgot to update it. Thanks for letting me know.

**Comment by andreicorpo** [comment]
No problem. Thank you for the prompt response! Have a nice weekend! 😄

**Comment by andreicorpo** [comment]
So I just noticed now that all my MRs seem to be added to `.gitlab_merge_requests.settings.json` as `todaysExcludedEvents`. I hope this helps.

**Comment by SimeonC** [comment]
@andreicorpo Upgraded to xbar and upgraded the plugin too, try the version in the linked MR #1608 and let me know if that works for you. (Note that it now uses xbar vars ✨ )

**Comment by andreicorpo** [comment]
It works perfectly now! Thank you so much!
