### ISSUE TITLE
Suggestion: Allow cycle speed

### ISSUE THREAD

**Issue by kenfasano** [matryer/xbar-plugins#1623]
I've got a stock ticker plugin that cycles between various symbols, but it cycles rather quickly, like every 5 seconds (the plugin is ticker.5m.sh, so it refreshes every 15 minutes). I'd like it to cycle slower, like once every 20 seconds. Thanks.

**Comment by matryer** [comment]
Please open this in github.com/matryer/xbar (there might already be one for this) because I agree it should allow you to control the cycle speed of a plugin.
