### ISSUE TITLE
unknown parameter error if there is a space in the fully qualified file name

### ISSUE THREAD

**Issue by muzammilrehman** [matryer/xbar-plugins#1626]
If the file name contains a space the error unknown parameter pops up. The fix is easy just add single quotes around the file name line [119](https://github.com/muzammilrehman/xbar-plugins/blob/878e24dcb49c3986fce6de4752a87caa9a0308bb/Tools/PagerDuty/pagerduty.30s.rb#L119) 

`                bash = "bash='#{File.expand_path(__FILE__)}' param1=#{option} param2=#{incident['id']}" unless incident['status'].eql?("test")
`

@frese

**Comment by muzammilrehman** [comment]
![Uploading Screenshot 2021-05-25 at 4.37.44 PM.png…]()

**Comment by frese** [comment]
Feel free to change it or do a PR.
I'm not using this plugin any longer in favour of this project https://github.com/trustpilot/pagerduty-notifier 😄

**Comment by muzammilrehman** [comment]
I dont have permission to create PR, that was my initial step
