### ISSUE TITLE
001-brew-services.10m.rb: 

### ISSUE THREAD

**Issue by carlosfrodriguez** [matryer/xbar-plugins#1635]
fao @eproxus - 
Does not display correctly in the menu bar, seams that terminal color codes does not play nicely in xbar

"[1m[32m3[30m/10" instead of e.g."3/10"

**Comment by eproxus** [comment]
Sorry, but I'm not using BitBar/Xbar anymore.

**Comment by jimeh** [comment]
@carlosfrodriguez I've submitted my replacement/rewrite of brew-services in #1717 which might solve your issue.

**Comment by carlosfrodriguez** [comment]
@jimeh Thanks!

**Comment by martin-braun** [comment]
Yes, it keeps starting and stopping. @jimeh thanks for [the fix](https://github.com/jimeh/xbar-plugins/blob/new-brew-services-plugin/Dev/Homebrew/brew-services.10m.rb), I hope it can be accepted soon.

**Comment by briantully** [comment]
> @carlosfrodriguez I've submitted my replacement/rewrite of brew-services in #1717 which might solve your issue.

Thanks so much for this @jimeh !!! Works like a charm and also fixes the menu bar from disappearing/reappearing every few seconds.
