### ISSUE TITLE
001-solaredge.5m.py: "malformed parameters: missing equals"

### ISSUE THREAD

**Issue by justingoeres** [matryer/xbar-plugins#1654]
fao @shaungrady - 

After inputting my solaredge_api_key & solaredge_site_id, running the plugin in xbar gives the following error:
![image](https://user-images.githubusercontent.com/17071464/124392923-f579cb80-dcc5-11eb-890a-12eae9d7d368.png)
> parse stdout: 001-solaredge.5m.py:3: malformed parameters: missing equals

Notably, it does work correctly from the shell:

> $ ~/Library/Application\ Support/xbar/plugins/001-solaredge.5m.py 
> ☀︎ 22.6 kWh @ 5.3 kW| font='SF Compact Text Regular'
> 
> 114 kWh this month | href:https://monitoring.solaredge.com/
> 3.21 MWh this year | href:https://monitoring.solaredge.com/
> 
> 1.64 tons CO₂ offset | href:https://monitoring.solaredge.com/

**Comment by shaungrady** [comment]
@justingoeres Huh, haven't seen that before. Didn't know about this xbar project, either—I'm still using BitBar without issue. I'll have a look when I can spare some time.

**Comment by justingoeres** [comment]
@shaungrady xbar is new to me, too – I just flipped over from bitbar once I realized xbar is apparently the replacement.

I have a couple plugins I wrote myself that work without issue. If I have a chance I'll poke at this, too. I'm sure it's something simple.

**Comment by dmgerman** [comment]
on a different plug-in, i tracked this problem. xbar seems to generate the error when a "|" character is part of a line to be displayed by xbar.
