### ISSUE TITLE
001-weather.15m.py: errors pop up

### ISSUE THREAD

**Issue by MilapNaik** [matryer/xbar-plugins#1662]
fao @seripap - 

shebang should be #!/usr/bin/env PYTHONIOENCODING=UTF-8 /usr/local/bin/python3 or else I got an error. Also, if you try to print out the entire week forecast with the latest version of xbar, there's an error. I'm not sure why.

**Comment by matryer** [comment]
@MilapNaik we'd happily accept a PR if you've manged to make it work?

**Comment by MilapNaik** [comment]
My location was in the US. I believe the file does contain UTF-8 characters originally.

**Comment by MilapNaik** [comment]
I think the other issue was that my python3 environment is different from most people's

**Comment by MilapNaik** [comment]
Actually, to be completely accurate, I have a function that gets your location from your computer IP and returns that as the given location. So maybe I added the UTF-8 characters from that. This was a long time ago so it's just now coming back to me
