### ISSUE TITLE
001-meta_package_manager.7h.py: 

### ISSUE THREAD

**Issue by valenokk** [matryer/xbar-plugins#1668]
fao @kdeldycke - Hi, I've noticed that "emojize=false" is not prepended with "|" in most lines and "refresh=true" is not prepended with "|" in "Upgrade all" section.

**Comment by matryer** [comment]
@valenokk maybe you can make the tweaks in a PR?

**Comment by kdeldycke** [comment]
I [just fixed the issue upstream](https://github.com/kdeldycke/meta-package-manager/commit/e054ccb1362cc6645d8cc532beadd4f4101afa19). I'll push a PR in the canonical `xbar-plugins` repository when I'll have the new `mpm` CLI released (in a couple of days I guess).

**Comment by kdeldycke** [comment]
mpm v4.2.0 has been released. The plugin that fixes this issue is ready to be merged at: https://github.com/matryer/xbar-plugins/pull/1702
