### ISSUE TITLE
Get xbar variables in Python

### ISSUE THREAD

**Issue by alvaroserrrano** [matryer/xbar-plugins#1673]
In order to develop plugins that benefit from variables set according to user preferences when they first install the plugin. What would be the correct way to get those values? I have seen the example that is provides in bash using ${}. In python I have tried both using os.getenv() and creating the <plugin_name>.1m.py.json.vars, but they do not seem to work. For example
```
#  <xbar.var>string(VAR_API_KEY=""): Api Key for plugin</xbar.var>
....
import os
API_KEY = os.getenv("VAR_API_KEY", "")
```

**Comment by matryer** [comment]
@alvaroserrrano you're doing it right, I think. It should come in via environment variables.

**Comment by matryer** [comment]
If memory serves, the file should be called `.vars.json`? Could be that.

**Comment by sprak3000** [comment]
I've also seen plugin authors use `os.environ.get` for the variables. Not familiar enough with python / python3 to know what if any difference might be.
