### ISSUE TITLE
Plugin for showing the local COVID-19 incidence (Germany only)

### ISSUE THREAD

**Issue by pdiegmann** [matryer/xbar-plugins#1674]
Hi all,

wrote a small plugin for me to show the local county-related COVID-19 incidence as well as the state-wide incidence and the last-updated date: https://github.com/pdiegmann/xbar-rki-lokale-inzidenzzahl.git

If you want to include it in your list of plugins, feel free to add it.

Thank you for your amazing app!

**Comment by matryer** [comment]
@pdiegmann Can you do a PR adding this? Also, please include an image of what the plugin looks like when installed.

**Comment by sprak3000** [comment]
@pdiegmann Did you ever open a PR for this plugin?
