### ISSUE TITLE
001-xrp-usd.py: 

### ISSUE THREAD

**Issue by ppeev** [matryer/xbar-plugins#1678]
fao @impshum - 

This happens after install. Tried restarting, doesn't help.

<img width="846" alt="image" src="https://user-images.githubusercontent.com/12800014/128782192-83dcc8a3-4b62-4579-ae72-42caca1214c3.png">

**Comment by impshum** [comment]
Noted. 

I need to go through most of my plugins. Thanks for bringing this to my attention.
