### ISSUE TITLE
gitlab_merge_requests.js: Author's ID in the code

### ISSUE THREAD

**Issue by Spaider** [matryer/xbar-plugins#1695]
@SimeonC what's the point to fetch your events in line 225 of [plugin source code](https://github.com/matryer/xbar-plugins/blob/257c4225ae97668701279849fa89644ec2932814/Dev/Gitlab/gitlab_merge_requests.js#L225)?

**Comment by SimeonC** [comment]
Haaaahhh, that's a complete miss on my end. It should be the userid from settings object. Thanks for pointing it out, I'll patch it tomorrow.

The point of that particular call is to display and branches that were pushed today but don't yet have MRs associated with them. I have to work in multiple projects so a "create MR from the branch I just pushed" feature is quite useful for me.
