### ISSUE TITLE
Issue with "Bluetooth Inspector " 001-bluetooth_inspector.10m.rb: 

### ISSUE THREAD

**Issue by bergel** [matryer/xbar-plugins#1719]
fao @RyanScottLewis - 

I recently updated to Monterey, and I get an error:

<img width="809" alt="image" src="https://user-images.githubusercontent.com/393742/140532849-c1a19874-8b1b-48d0-b57c-8e35fd686132.png">

**Comment by sprak3000** [comment]
Fixed in #1945
