### ISSUE TITLE
Acquia Cloud Plugins

### ISSUE THREAD

**Issue by grasmash** [matryer/xbar-plugins#1722]
Hi. I've written two plugins for [Acquia Cloud ](acquia.com) that I'd like to contribute. 

1. Acquia Cloud IDEs: List Acquia Cloud IDEs.
2. Acquia Cloud Applications: List Acquia Cloud Applications

Please let me know what is required in order to merge these. Thanks!

**Comment by sprak3000** [comment]
@grasmash Was a PR ever submitted for these plugins?
