### ISSUE TITLE
Number of twitter followers and members of a Discord server. 

### ISSUE THREAD

**Issue by purpleglow** [matryer/xbar-plugins#1725]
is there a plugin for this? It would be really useful. I wish there was a search feature here so I can search instead of having to click every single category

**Comment by sprak3000** [comment]
No plugins for this currently. Given the state of the Twitter API now, unlikely one for that would be created. Discord might be a possibility, but no one seems to have found this issue in over a year. You might be better off creating a new issue just for your Discord request. Include what exactly you would want the plugin to do. Just number of members of a Discord server? See who is online? Multi Discord server support? The more details the better...
