### ISSUE TITLE
unknown parameter: root

### ISSUE THREAD

**Issue by Aleksandern** [matryer/xbar-plugins#1742]
Some script has the following line:
`echo "Refresh | refresh=true terminal=false root=true"`

xbar shows error
`parse stdout: scriptname: unknown parameter: root`

So the `root` parameter is not supported anymore?

**Comment by sprak3000** [comment]
For reference, the script in question is `System/cpu-usage-kill.5s.sh`.

**Comment by sprak3000** [comment]
c.f., #1846
