### ISSUE TITLE
001-bluetooth_inspector.10m.rb.off: 

### ISSUE THREAD

**Issue by energio** [matryer/xbar-plugins#1753]
fao @RyanScottLewis - 
<img width="849" alt="Schermata 2022-01-14 alle 08 58 18" src="https://user-images.githubusercontent.com/182047/149471924-ebc7789c-0a4a-40ff-a3c2-a113d28153e4.png">
after update macos to Monterey

**Comment by sprak3000** [comment]
Fix has been applied to account for changes in how system profiler returns the information.
