### ISSUE TITLE
002-brew-updates.1d.sh: - Upgrade to allow /opt location

### ISSUE THREAD

**Issue by a-c-m** [matryer/xbar-plugins#1761]
fao @killercup - 

Script fails if you have brew installed to non-standard location (i.e. not in `/usr/local/bin/brew`) which is needed on some systems e.g. M1 Macs.

Below is an updated version which should work in both `usr` and `opt` install locations. I did also try using $(which brew), but that didn't work in the bar. Also, i updated a little the emoji used for updates (📦) as well as having a dedicated "ok" emoji (☑️), i also commented out the "ok" state, to save space.

```
#!/bin/bash
# <xbar.title>Homebrew Updates</xbar.title>
# <xbar.author>killercup</xbar.author>
# <xbar.author.github>killercup</xbar.author.github>
# <xbar.desc>List available updates from Homebrew (OS X)</xbar.desc>

exit_with_error() {
  echo "err | color=red";
  exit 1;
}

if [ -f /usr/local/bin/brew ]; then 
  BREWBIN=/usr/local/bin/brew
else
  BREWBIN=/opt/homebrew/bin/brew
fi

$BREWBIN update > /dev/null || exit_with_error;

PINNED=$($BREWBIN list --pinned);
OUTDATED=$($BREWBIN outdated --quiet);

UPDATES=$(comm -13 <(for X in "${PINNED[@]}"; do echo "${X}"; done) <(for X in "${OUTDATED[@]}"; do echo "${X}"; done))

UPDATE_COUNT=$(echo "$UPDATES" | grep -c '[^[:space:]]');

if [ -n "$UPDATES" ]; then
  echo "📦 $UPDATE_COUNT | dropdown=false"
  echo "---";
  echo "Upgrade all | bash=$BREWBIN param1=upgrade terminal=false refresh=true"
  echo "$UPDATES" | awk '{print $0 " | terminal=false refresh=true bash=$BREWBIN param1=upgrade param2=" $1}'
else
  # Comment back in, if you want to see no packages need updating
  # echo "☑️ | dropdown=false"
fi
```

**Comment by sprak3000** [comment]
@a-c-m 

This plugin has been deprecated in favor of a new one recently merged. It provides a variable allowing you to set the Homebrew path for your machine. The plugin browser hasn't been updated yet, but you can grab the [source directly](https://raw.githubusercontent.com/matryer/xbar-plugins/main/Dev/Homebrew/brew-updates.1h.rb).
