### ISSUE TITLE
notifications.30s.py: Current xbar version downloads a version of the script that does not include the xbar vars

### ISSUE THREAD

**Issue by funkymonkeymonk** [matryer/xbar-plugins#1764]
fao @flesch - 

Hey folks. I think this could be easier to use if the comment lines to support xbar variables were added. I'll submit a PR for this.

**Comment by funkymonkeymonk** [comment]
Sorry to misfile, I see this has already been fixed on master. For some reason when I downloaded the plugin from the xbar plugin browser it got a version that didn't include the comments. I'll try to dig into why I got an older version of the script.

**Comment by funkymonkeymonk** [comment]
Just confirmed that I downloaded an older version on a brand new install

# <xbar.version>v3.0.2</xbar.version>

This looks like an issue with xbar's plugins browser and not likely the plugin itself.

**Comment by sprak3000** [comment]
Looks like plugin browser is pulling the latest version now. Closing.
