### ISSUE TITLE
slack-team-notifications.1m.js: 

### ISSUE THREAD

**Issue by eureporter** [matryer/xbar-plugins#1773]
fao @benjifs - 

Hi, this plugin is not marking all read messages when selecting "mark all as read"

Any reason for this? I've used the "Bitbar-Slack-OAuth" App to generate my token if this helps.

**Comment by benjifs** [comment]
Sorry, I had missed this. Dumb typo on my part. I just created a PR for this fix which should hopefully be merged soon
