### ISSUE TITLE
001-circleci-check.5m.py: "No module named requests"

### ISSUE THREAD

**Issue by arkban** [matryer/xbar-plugins#1781]
fao @fsegouin - 

I tried to install the [CircleCI Check](https://github.com/matryer/xbar-plugins/blob/main/Dev/circleci-check.5m.py) plugin and it fails with the following:
![image](https://user-images.githubusercontent.com/1063049/155181612-a54362b0-6325-413f-a97c-1b218d5a55e3.png)

I attempted to install the package locally 
```shell
~ pip list
Package            Version
------------------ ---------
...
requests           2.27.1
...
```
yet it does not resolve the issue : (

Related issues:
* https://github.com/matryer/xbar-plugins/issues/294

**Comment by carlast22** [comment]
Hi, I'm using the latest version from xbar: v2.1.7-beta and still get the same issue. Is there any solution for this?
