### ISSUE TITLE
Why my script shows nothing in xbar but success in terminal

### ISSUE THREAD

**Issue by p1k0pan** [matryer/xbar-plugins#1800]
my script easily print current yabai space label
```
#!/usr/bin/env bash
PATH=$PATH:/usr/local/bin
space=$(yabai -m query --spaces --space | jq ".label")
echo ${space}
```
The xbar on menubar turns to blank and show nothing. This script running ok in terminal.

I have also test `echo "test"` work on xbar.

Maybe I miss something?

**Comment by steven-lang** [comment]
I fixed it by modifying `PATH=$PATH:/usr/local/bin` to `PATH=$PATH:/usr/local/bin:/opt/homebrew/bin`.

**Comment by SnowRocket74** [comment]
Hi,
I've got a similar issue.
The result print correctly in bash but not in the menubar.

Do you have a solution for this ?

**Comment by p1k0pan** [comment]
> 

Sry I don't even using Xbar for now. If just want to know the number of current space, I use SpaceId for mac without any configuration
