### ISSUE TITLE
001-homebrewcask.1d.sh: 

### ISSUE THREAD

**Issue by ricounet67** [matryer/xbar-plugins#1804]
fao @srdgh - 

I get an error when running the Homebrew cask plugin
![Sans titre](https://user-images.githubusercontent.com/1090484/160351194-f7731b4a-b0a2-4c89-b976-5314a44237dc.png)

**Comment by kdeldycke** [comment]
May I suggest using [`meta_package_manager.7h.py`](https://github.com/matryer/xbar-plugins/blob/main/Dev/meta_package_manager.7h.py) as an alternative? See the documentation at: https://kdeldycke.github.io/meta-package-manager/xbar.html

**Comment by sprak3000** [comment]
@ricounet67 

We recently merged in another alternative offering the same functionality and more. The plugin browser has not been updated yet to include it, but you can grab the [source directly](https://raw.githubusercontent.com/matryer/xbar-plugins/main/Dev/Homebrew/brew-updates.1h.rb) to install it. Comes with a variable allowing you to set the Homebrew path based on your machine -- Intel vs Apple M1 silicon.
