### ISSUE TITLE
Does not work in xbar after installation

### ISSUE THREAD

**Issue by 0xDEnYO** [matryer/xbar-plugins#1805]
Hi, 

i've just installed xbar to use this gas tracker and after adding it to xbar, the following errors are shown:

![image](https://user-images.githubusercontent.com/77058885/160881552-e36315f3-94da-43a1-99cb-f2309b9748fc.png)

What am I missing or what do I have to do to make this work?

Cheers,
Daniel

**Comment by haowang1013** [comment]
Need to change the url to https://etherchain.org/api/gasnow

**Comment by sprak3000** [comment]
@0xDEnYO 

We recently merged the change @haowang1013 mentioned. You can grab the [latest source](https://raw.githubusercontent.com/matryer/xbar-plugins/main/Cryptocurrency/Ethereum/gasnow.10s.sh) for the plugin for the fix.
