### ISSUE TITLE
JSON files should be ignored in plugins folder

### ISSUE THREAD

**Issue by dzg** [matryer/xbar-plugins#1834]
Some of my scripts generate JSON in the plugins folder, and xbar tries to load them with error `chmod +x ...`

Seems JSON should be ignored – they couldn't possibly generate output.

**Comment by sprak3000** [comment]
I believe this has been fixed. If it is still happening after an upgrade, please reopen this and send more details -- version of xbar, sample file name / paths of JSON files, etc.
