### ISSUE TITLE
Script not running in xbar app or console

### ISSUE THREAD

**Issue by WizoneDE** [matryer/xbar-plugins#1835]
installed via xbarapp the script isn't running. it is only showing the red X.

All I get when running it via console is:

`% VAR_SUBMENU_lAYOUT="false" '/Users/*****/Library/Application Support/xbar/plugins/001-meta_package_manager.7h.py'
❌ | dropdown=false
---
Usage: mpm outdated [OPTIONS] | color=red font=Menlo size=12 trim=false emojize=false
Try 'mpm outdated --help' for help. | color=red font=Menlo size=12 trim=false emojize=false
 | color=red font=Menlo size=12 trim=false emojize=false
Error: No such option: --cli-format | color=red font=Menlo size=12 trim=false emojize=false`

starting mpm itself in console is working fine.

**Comment by sprak3000** [comment]
@WizoneDE 

The fix @kdeldycke mentioned has been merged. You'll need to grab the latest source. I believe you can uninstall and reinstall to do this. If not, you can grab the [source directly](https://raw.githubusercontent.com/matryer/xbar-plugins/main/Dev/meta_package_manager.7h.py).
