### ISSUE TITLE
001-password_bar.5m.php: 

### ISSUE THREAD

**Issue by christophholzapfel** [matryer/xbar-plugins#1838]
fao @gomedia-adi - 

Hi Adi, after migrating my macOS to my new M1 machine with macOS 12.4 I can not use your xbar-Plugin password-bar anymore. I only see the attached message:
<img width="405" alt="xbar-message" src="https://user-images.githubusercontent.com/108024464/175112950-dc392013-1542-4440-8f7d-7a59fb5f53b7.png">
Do you have any idea how to fix this and get password-bar back running?

Cheers,
Christoph

**Comment by gomedia-adi** [comment]
Hi Christoph,

password_bar requires PHP and unfortunately, as of MacOS Monterey 12.4, it's no longer preinstalled.  I haven’t done it yet but I believe the recommended method is to use Homebrew.  

Adi

**Comment by sprak3000** [comment]
@christophholzapfel 

The PHP manual has [instructions](https://www.php.net/manual/en/install.macosx.packages.php) for installing via Homebrew. There are other methods for installing it -- [asdf](https://github.com/asdf-community/asdf-php), etc. Brew is likely the easiest choice if you just need it for the plugin.
