### ISSUE TITLE
001-rss.15m.php: open does not work

### ISSUE THREAD

**Issue by pietvanzoen** [matryer/xbar-plugins#1851]
fao @alesf - 

Running in terminal, the open command on an rss item works fine. But when running in xbar it seems to fail. (Nothing happens).

https://github.com/matryer/xbar-plugins/blob/8ab7ceb1edf33d61a5a1452ced0c769dd096fa92/Web/rss.15m.php#L44

I'm not sure if there's a way to see the error being thrown in xbar. Seems like maybe a user permissions issue? Could totally be something to do with my setup. ¯\_(ツ)_/¯

Any tips appreciated.

**Comment by alesf** [comment]
xbar puts plugins in ~/Library/Application Support/xbar/plugins folder and it does not play nicely with spaces in the path. I tried to do a quick fix but nothing seems to be working so far.

Since PHP is not bundled with macOS anymore it would be better to write the plugin in bash or node anyway.

**Comment by KenSmz** [comment]
After installing PHP via Homebrew, the script will work by making the following three modifications:

line 1: `#!/usr/bin/env -S PATH="${PATH}:/opt/homebrew/bin:/usr/local/bin" php`
line 200: `echo "bash=".PHP_PATH." param1=\"".SCRIPT_PATH."\" param2=$guid\n";`
line 216: `echo "bash=".PHP_PATH." param1=\"".SCRIPT_PATH."\" param2=MARK_ALL_AS_READ\n";`
