### ISSUE TITLE
001-bandwidth.1s.sh: 

### ISSUE THREAD

**Issue by alexcphoenix** [matryer/xbar-plugins#1874]
fao @skibz - 

hi there, 
this plugin cannot output results in the menu bar. 
after tried run in terminal, it returns "ifstat: cannot find found..." 
I've installed zsh, version 5.8.1, 
now what should I do. 

Thanks in advance

**Comment by skibz** [comment]
https://github.com/matryer/xbar-plugins/blob/main/Network/bandwidth.1s.sh#L8

**Comment by sprak3000** [comment]
@alexcphoenix 

You can install `ifstat` via [Homebrew](https://brew.sh/):

```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew install ifstat
```
