### ISSUE TITLE
Gitlab Merge request install issue

### ISSUE THREAD

**Issue by davidattias** [matryer/xbar-plugins#1876]
@SimeonC When I install gitlab merge request plugin, I have this error, any idea?
I have xbar 2.1.7-beta
<img width="1300" alt="Screenshot 2022-11-22 at 11 52 33" src="https://user-images.githubusercontent.com/1429245/203295991-9d8a4e13-526e-4745-aee0-f729ca899b8a.png">

**Comment by SimeonC** [comment]
Ahhh, I'm guessing this is that the bitbar node package got upgraded to ESM in v2 probably (the warning at the top).

I wrote the plugin to be es5 (before esm got traction) and only compatible with bitbar node plugin v1.

I don't use gitlab anymore but I'd created a ESM compatible version for github (which is still pending merge...) here: https://github.com/matryer/xbar-plugins/pull/1752/files
You can probably take the changes in there to get the gitlab one to work again.

**Comment by davidattias** [comment]
Thank you, I will try. DavidLe 24 nov. 2022 à 01:30, Simeon Cheeseman ***@***.***> a écrit :﻿
Ahhh, I'm guessing this is that the bitbar node package got upgraded to ESM in v2 probably (the warning at the top).
I wrote the plugin to be es5 (before esm got traction) and only compatible with bitbar node plugin v1.
I don't use gitlab anymore but I'd created a ESM compatible version for github (which is still pending merge...) here: https://github.com/matryer/xbar-plugins/pull/1752/files
You can probably take the changes in there to get the gitlab one to work again.
