### ISSUE TITLE
age-ticker.1m.py: 

### ISSUE THREAD

**Issue by ramakrushna137** [matryer/xbar-plugins#1883]
fao @garythung - 
Even after i added my age this plugin isn't working
 
![image](https://user-images.githubusercontent.com/72355599/209063860-a5535e6b-7074-46fd-be67-af2f2989dda6.png)
![image](https://user-images.githubusercontent.com/72355599/209063890-15d51969-8ead-4f2a-ae3d-5ed1b2ae7142.png)

**Comment by garythung** [comment]
Hey sorry, I don't use xbar anymore so I can't debug deeply. I think the file should be named `age-ticker.1s.py` though. I'm not sure.
