### ISSUE TITLE
001-homebrewcask.1d.sh: Brew binary location incorrect on Apple Silicon

### ISSUE THREAD

**Issue by caj380** [matryer/xbar-plugins#1904]
fao @srdgh - 

On Apple Silicon Macs the path for the brew binary is `/opt/homebrew/bin/brew` but the script currently uses `/usr/local/bin/brew` which (I think) is only for Intel Macs.

I replaced all occurrences of the path and it fixed the issue for me.

**Comment by sprak3000** [comment]
@caj380

That plugin has been removed in favor of a new Ruby based plugin that covers the same and more functionality. It was recently [merged](https://github.com/matryer/xbar-plugins/pull/1715/files) but is not yet available in the plugin browser. You would need to grab the source from the PR / repo directly. It includes a variable to set the Homebrew path.
