### ISSUE TITLE
New Plugin request - power-wattage-advanced.sh

### ISSUE THREAD

**Issue by matanbaruch** [matryer/xbar-plugins#1911]
Hey,
I'm unable to submit a PR getting rejected, Adding this here
Let me know where to submit it. 

Consumption 🔌 Replenishment (From adapter)

![](https://i.imgur.com/OpKXCQy.png)
```
#!/bin/bash
#
# <xbar.title>Power Wattage Advanced</xbar.title>
# <xbar.version>v0.1</xbar.version>
# <xbar.author>matanbaruch</xbar.author>
# <xbar.author.github>matanbaruch</xbar.author.github>
# <xbar.desc>The AC Power adapter wattage consumption and current for macos</xbar.desc>
# <xbar.image>https://i.imgur.com/OpKXCQy.png</xbar.image>
# <xbar.dependencies></xbar.dependencies>
# <xbar.abouturl>github.matan-baruch.com</xbar.abouturl>

power_consumption=$(ioreg -rw0 -c AppleSmartBattery | grep BatteryData | grep -o '"SystemPower"=[0-9]*' | cut -c 16- | xargs -I %  lldb --batch -o "print/f %" | grep -o '$0 = [0-9.]*' | cut -c 6-9)

power_wattage=$(ioreg -rw0 -c AppleSmartBattery | grep BatteryData | grep -o '"AdapterPower"=[0-9]*' | cut -c 16- | xargs -I %  lldb --batch -o "print/f %" | grep -o '$0 = [0-9.]*' | cut -c 6-9)

if [ -z "$power_wattage" ]
then
  echo "🔋"
else
  echo "${power_consumption}W🔌${power_wattage}W"
fi

echo "---"
echo "Refresh... | refresh=true"
```

**Comment by sprak3000** [comment]
@matanbaruch 

What errors are you getting opening a PR? Did you fork the repository to do add your plugin? If you still have an issue opening a PR, let me know.

**Comment by matanbaruch** [comment]
Yes, I forked it in order to add this to my plugins :\ 
I will try again tomorrow.

**Comment by sprak3000** [comment]
@matanbaruch 

Where I haven't heard back from you, I went ahead and merged this via a PR from my fork. I set the plugin to refresh itself every 30 minutes. The plugin browser has to be updated manually, but I do not have the ability to run that process just yet. Plugin won't show up until that is taken care of.

Thank you for your submission!
