### ISSUE TITLE
001-toggl.1m.js: Several tiny adjustments needed

### ISSUE THREAD

**Issue by s00500** [matryer/xbar-plugins#1915]
fao @SCdF - 

${process.argv[1]} needs quotes

Also toggl's main api changed to track.toggl.com 

Both super fast fixed :-)

**Comment by SCdF** [comment]
Hey, I don't use xbar anymore. Are you able to make the changes you want?

**Comment by s00500** [comment]
Sure, I can submit a PR here :-) Thanks for building the plugin in the first place! (I dont use a lot of it but I was able to make all the mods I wanted very quickly)
