### ISSUE TITLE
kubeswitcher.1m.sh: issue with profile or environment variables? Plugin only works if xbar is launched via terminal

### ISSUE THREAD

**Issue by brunopereira7** [matryer/xbar-plugins#1922]
**OS:** MacOS - Ventura 13.2.1
**Processor:** Apple M1
**xbar version:** 2.1.7-beta
**plugin:** kubeswitcher.1m.sh by [Elias Abacioglu (@Raboo on GitHub)](https://xbarapp.com/docs/contributors/Raboo.html)

**Description:** I'm not sure if the issue could be related to xbar itself, or even something that I'm missing, but I'm trying to set up xbar with ['Kubeconfig Namespace & Context Switcher'](https://xbarapp.com/docs/plugins/Dev/Kubernetes/kubeswitcher.1m.sh.html) plugin, and it's not working as expected **when xbar is launched via a standard application**.  

For detailed information see: https://github.com/matryer/xbar/issues/877

FYI: @Raboo

**Comment by Raboo** [comment]
My xbar is started as a standard application.
Easiest way to troubleshoot the plugin is to execute it directly in a terminal to see the output and to see if there are any errors.

Perhaps even run with `bash -x ./plugin.sh` for more visibility into what the script does.

**Comment by brunopereira7** [comment]
I @Raboo first of all thanks for the plugin and your response.

I didn't add here all the details that you can find -> https://github.com/matryer/xbar/issues/877 but your script seems to be ok if I run it with the terminal:

![image](https://user-images.githubusercontent.com/37114503/222430790-8afa55f8-e4cd-479b-bf95-6749b73eb353.png)

The output seems ok:
![image](https://user-images.githubusercontent.com/37114503/222430889-c32e6eec-36a3-4d20-9db3-3ab2b7a3402e.png)


Unfortunately, I don't understand why it did not work when xbar is launched via applications / or started at login (Namespace and Context empty):

![image](https://user-images.githubusercontent.com/37114503/222432718-946c91ef-dabb-4b64-912d-a29667717e69.png)

![image](https://user-images.githubusercontent.com/37114503/222432754-1aa01639-97cb-4276-b6c7-f5b4ce5069bc.png)

**Comment by Raboo** [comment]
hmm, I don't know why and what would change depending on how you start xbar.
Perhaps it's cause when xbar is started via UI or autostart it doesn't source `~/.profile`, `~/.bashrc` or `~/.bash_profile`.

Try changing line `PATH=$PATH:/usr/local/bin` to `PATH=$PATH:/usr/local/bin:/opt/homebrew/bin` in kubeswitcher.sh

I noticed I have both _/usr/local/bin/kubectl_ and _/opt/homebrew/bin/kubectl_ on my laptop, would explain why I haven't encountered this problem.

**Comment by brunopereira7** [comment]
I've already tried what you mentioned but unfortunately didn't fix the issue 😞 

By the way, a colleague has successfully set up xbar with kubeswitcher plugin; everything works out of the box with the following setup:
OS: MacOS - Monterrey 12.6.2 (21G320)
Processor: Intel
xbar version: 2.1.7-beta

**Comment by Raboo** [comment]
Well I have a M1 Pro running on Ventura and 2.1.7-beta.

Try changing this
```
KUBECTL=$(command -v kubectl)
```

to this
```
KUBECTL=$(/usr/bin/command -v kubectl)
```

Also are you running kube config (~/.kube/config) in an non-default path (i.e. are you using $KUBECONFIG to configure a different path for your kube config file?)?

**Comment by brunopereira7** [comment]
Changing `KUBECTL=$(command -v kubectl)` to `KUBECTL=$(/usr/bin/command -v kubectl)` didn't solve the problem on my end. 

Concerning kube config, I'm using a non-default path indeed: 

```
└── ~/.kube
    ├── dlc-nonprod.kubecfg
    ├── dlc-prod.kubecfg
    └── sandbox.kubecfg
```

```bash
~ ❯ echo $KUBECONFIG                                                                                                                                                                                                                       
/Users/miguebru/.kube/sandbox.kubecfg:/Users/miguebru/.kube/dlc-nonprod.kubecfg:/Users/miguebru/.kube/dlc-prod.kubecfg
```

**Comment by Raboo** [comment]
I guess you should add `KUBECONFIG=/Users/miguebru/.kube/sandbox.kubecfg:/Users/miguebru/.kube/dlc-nonprod.kubecfg:/Users/miguebru/.kube/dlc-prod.kubecfg` to the script.

**Comment by sprak3000** [comment]
@Raboo 

Does https://github.com/matryer/xbar-plugins/pull/1925 close this issue?

**Comment by Raboo** [comment]
@sprak3000 I think so, but @brunopereira7 hasn't answered yet. But I think it should.

**Comment by brunopereira7** [comment]
Hey guys, definitely it's weird; I've tested with the last version of the script and even added a new menu entry to debug the env `echo "Kubeconfig: ${KUBECONFIG}"` but unfortunately, it's not working. 

![image](https://user-images.githubusercontent.com/37114503/224280088-f83ed11e-946c-435e-9050-b7dd63919dbd.png)

As a workaround, I'm simply launching the app via terminal `open -a xbar.app` and everything works as expected.

**Comment by Raboo** [comment]
https://github.com/matryer/xbar-plugins/pull/2035 should perhaps close this as it adds ability to inject the KUBECONFIG from the normal bash and zsh places.
However the script seems to have issues to switch between contexts from multiple files now instead (https://github.com/matryer/xbar/issues/877).
I will try to figure it on that issue.
