### ISSUE TITLE
How to contribute a plugin?

### ISSUE THREAD

**Issue by the-holger** [matryer/xbar-plugins#1928]
Hi all!

I've spent the last day to write a plugin to manage ZeroTier networks and would like to share it. The - maybe stupid - question I couldn't figure out myself reading the contribution guidelines is: how do I do that? Fork xbar-plugins and add mine and open a pull request? Post the link to the repo somewhere?

Thank you!
Holger

**Comment by sprak3000** [comment]
@the-holger 

Yes, you fork the repository, create a branch with your changes, and then issue a pull request against this repository. The [official docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) have a good run through on how to open a pull request. If you have any issues, reach out to me; we'll get things sorted in some fashion.

Before you open your pull request though, make sure your plugin has the following:

- The execute permission applied to the script file(s). This is typically done by performing `chmod +x <filename>`.
- An `<xbar.image>` metadata tag containing a link to a screenshot of your plugin in action.

Hope this helps! Again, feel free to reach out if you have more questions.

**Comment by sprak3000** [comment]
@the-holger 

Do you still need assistance, or could we close this out?
