### ISSUE TITLE
enphase_envoy.4m.rb: 

### ISSUE THREAD

**Issue by aminorjourney** [matryer/xbar-plugins#1950]
fao @grzegorz914 - 

Latest version of Enphase Envoy requires access token to use API.
(https://enphase.com/download/iq-gateway-access-using-local-apis-or-local-ui-token-based-authentication-tech-brief)

**Comment by grzegorz914** [comment]
this is only created for Envoy FW <= D5.0.62

**Comment by sprak3000** [comment]
@aminorjourney @grzegorz914 

I'm not finding this plugin in the repo. Is this still something being maintained here?
