### ISSUE TITLE
Adding a New System Information Plugin

### ISSUE THREAD

**Issue by pafera** [matryer/xbar-plugins#1973]
After finding that none of the existing plugins fit my usage, I wrote a simple one that I would like to add to the repository.

However, I had decided as a matter of principle to stop using my Github account when I found out that Microsoft was scraping all of my GPL 3 code to use in CoPilot, so I was wondering if I could just post the plugin here and have someone add it to the repository instead of opening a pull request instead. ;)

Just rename .txt to .py to run it.

[systeminfo.1s.txt](https://github.com/matryer/xbar-plugins/files/11857736/systeminfo.1s.txt)

**Comment by sprak3000** [comment]
@pafera 

While I can certainly add it to the repo, are you sure you want to do this? If you aim is to not have your code used in CoPilot training data, having it in this repo seems to run counter to that where they likely will be able to use it via its inclusion here.

If you do want me to go ahead, let me know.

**Comment by pafera** [comment]
Although I personally do not agree with CoPilot, I also feel that this is such a simple script that it would not make much of a difference to the training data, and that it would benefit more people than it would harm by having it in this repository. 

As such, please go ahead and add it. I have included an updated version here. :)

[systeminfo.1s.txt](https://github.com/matryer/xbar-plugins/files/11932186/systeminfo.1s.txt)

**Comment by sprak3000** [comment]
@pafera 

I've gone ahead and added the plugin. If possible, could you update the image to include what it looks like with the menu expanded? That will let potential users of the plugin know more details are available prior to install. You can just use the same link. If not, no worries.

Thank you for your submission.

**Comment by pafera** [comment]
The screenshot has been updated.

Thanks for all of your hard work in making OSX a bit more hospitable for us Linux folks. Best wishes for the future!
