### ISSUE TITLE
001-redditnotify.30s.py: Error when running

### ISSUE THREAD

**Issue by TheMin3s** [matryer/xbar-plugins#1991]
fao @Shugabuga - 

When opening the plugin in the menu bar, it shows the error "exit status 127: env: python; No such file or directory

When running in Terminal, it shows
` '/Users/<my username>/Library/Application Support/xbar/plugins/001-redditnotify.30s.py'`

`<my username>@<hostname> ~ %  '/Users/<my username>/Library/Application Support/xbar/plugins/001-redditnotify.30s.py`

`'env: python: No such file or directory`

This is in MacOS Sonoma 14.0 (Release Candidate).

**Comment by sprak3000** [comment]
@TheMin3s 

Apple moved to python3 at least an OS X version or two ago. Try editing the script to have this as the first line:

```
#!/usr/bin/env -S PATH="${PATH}:/opt/homebrew/bin:/usr/local/bin" python3
```

The above should attempt to find python3 as either the macOS installed version, installed by Homebrew on an Intel based Mac, or installed by Homebrew on an M1 based Mac. If you use asdf or other version management for python installs, add the path for that to the line.

Let me know if this works for you.

**Comment by pythoninthegrass** [comment]
Thanks for posting the solution @sprak3000! My shebang looks like this now due to xbar not finding my [asdf](https://asdf-vm.com/) python runtime:
```py
#!/usr/bin/env -S PATH="${HOME}/.asdf/shims:/opt/homebrew/bin:/usr/local/bin:${PATH}" python3
```

Would be better if it was possible to specify the path to the interpreter in the GUI. Took me a while to debug the path via
```py
import os
path = [path for path in os.environ.get('PATH').split(':')]
path = ':'.join(path)
print("PATH")
print("---")
print(path)
```

**Comment by sprak3000** [comment]
> Would be better if it was possible to specify the path to the interpreter in the GUI. Took me a while to debug the path via

Probably best to ask that in the [main app repo](https://github.com/matryer/xbar). I'm sure it is possible, but the drawback / difficulty would be in having to write that into each script you enable. What I've thought could be helpful would be to have the GUI detect various things like python, etc. and display them as help / suggestions on how to get a script working if it isn't.

**Comment by pythoninthegrass** [comment]
Fair enough! Thanks again!
________________________________
