### ISSUE TITLE
001-pubmed.py: 

### ISSUE THREAD

**Issue by detlefobal** [matryer/xbar-plugins#2032]
fao @ozturan - 
 File "/Users/obal/Library/Application Support/xbar/plugins/001-pubmed.py", line 12, in <module>
    import urllib2
ModuleNotFoundError: No module named 'urllib2'

**Comment by detlefobal** [comment]
where do I find the urllib2 module?

**Comment by sprak3000** [comment]
@detlefobal 

Are you running python3? That removed the `urllib2` module in favor of breaking things up into separate modules (c.f., [docs](https://docs.python.org/2/library/urllib2.html)).

Script may need to be uplifted for python3 support.

**Comment by detlefobal** [comment]
Yes, I am running python3, can you help me modifying the script?

**Comment by ozturan** [comment]
OK, I pushed it: https://github.com/matryer/xbar-plugins/commit/604b13c581688bea5960762bf02c3bebb682d64b. It should work now.

**Comment by detlefobal** [comment]
perfect, will try...

**Comment by sprak3000** [comment]
@detlefobal 

Are we good to close this one out?

**Comment by detlefobal** [comment]
Hi Luis,
Sure. Thanks,
Detlef
