### ISSUE TITLE
001-rss.15m.php: XML glitch—please help!

### ISSUE THREAD

**Issue by danlarge** [matryer/xbar-plugins#2065]
fao @alesf, @KenSmz - 

Hi guys—this looks like just the app I need, but I'm suffering from a problem of some kind, and despite my best efforts to find a fix using online advice (I'm no coder—I just learn by trial and error!), I am clearly  doing something wrong.

Tearing my hair out!

---

**FULL CONTEXT**

**1.** System report attached

[SYSTEM REPORT 241016.pdf](https://github.com/user-attachments/files/17388070/SYSTEM.REPORT.241016.pdf)

**2.** Installed _XBar_

**3.** Opened and installed _Simple RSS Reader_ from https://xbarapp.com/docs/plugins/Web/rss.15m.php.html

**4.** Opened code in _Xcode_

**5.** Changed the following lines:

define('FEED_URL', 'http://feedpress.me/sixcolors?type=xml');
define('ITEM_LIMIT', 25);

TO

define('FEED_URL', 'https://www.mi5.gov.uk/UKThreatLevel/UKThreatLevel.xml');
define('ITEM_LIMIT', 1);

**6.** Result is attached GIF ("[yellow ! shield] rss.15m.php" in menu bar, which drops down on left click to message "exit status 255")

![CleanShot 2024-10-16 at 02 38 45](https://github.com/user-attachments/assets/3df42660-9122-4b73-b7f7-6fb7e799e69e)

---

I have made no other changes to either your code or Xbar. They are both freshly installed after I wiped my own attempts at resolving the issue, including wiping any detritus left in the Library.

Please can you—or someone else who can identify the problem—help me out here?

Thank you very much in advance for your time and assistance. It's the right app for sure—just need to sort this glitch out!

**DL**

**Comment by sprak3000** [comment]
@danlarge 

It appears the issue is the server you are hitting is doing some blocking of traffic. It returns a `403 Forbidden` response when running the script. Guessing they are blocking any traffic not coming from trusted sources like a web browser, etc. Not surprising since it is an MI5 site...

I'm tinkering with it to see if there are headers I can set to get it to respond.

**Comment by sprak3000** [comment]
@danlarge 

I found a way to get the script to work with the URL you want to use. However, it is not a universal solution; it breaks trying other RSS feeds it typically reads properly.

If you do want to use the plugin with that URL and for nothing else, you can make the following edits to the script.

Replace this line in the `public function load($url)` function:

```
        $feed_data = @file_get_contents(FEED_URL);
```

with

```
//         $feed_data = @file_get_contents(FEED_URL);
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, FEED_URL);
        curl_setopt($ch, CURLOPT_HEADER, false);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_HTTPHEADER, [
            'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:132.0) Gecko/20100101 Firefox/132.0',
            'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
            'Accept-Language: en-US,en;q=0.5',
            'Sec-GPC: 1',
        ]);

        $feed_data = curl_exec($ch);

        curl_close($ch);
```

Then, replace this line in the `getItemElement($item, $element)` function

```
return trim($item->getElementsByTagName($element)->item(0)->firstChild->nodeValue);
```

with

```
            $node = $item->getElementsByTagName($element)->item(0);
            if ($node === null) {
                return '';
            }
            return trim($item->getElementsByTagName($element)->item(0)->firstChild->nodeValue);
```

Reload the script, and you should be all set.

**Comment by sprak3000** [comment]
@danlarge 

Have you tried my proposed fix? Going to close this out in another week if no response.
