### ISSUE TITLE
re: internal-ip

### ISSUE THREAD

**Issue by Kamik423** [matryer/xbar-plugins#938]
FAO: (@matryer)

not working for me. fix: `ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'`

**Comment by matryer** [comment]
LGTM, do you want to submit a PR and put your name as the author?

**Comment by sprak3000** [comment]
@Kamik423 & @matryer 

While the command in the issue details does grab the internal IP address, the plugin's original intent appears seems to do two things:

1. Display the internal IP address in the menu bar.
1. Display the interface / adapter details in the actual menu.

I've opened a PR that should address both intents.

Hope this helps.
