### ISSUE TITLE
re: Coinbase.com Your Balance

### ISSUE THREAD

**Issue by AdamVyborny** [matryer/xbar-plugins#943]
FAO: (@matryer)
jq command not found - even though jq is installed...

**Comment by sprak3000** [comment]
@AdamVyborny 

Did you ever get this sorted out?

**Comment by AdamVyborny** [comment]
@sprak3000 yes, I buy new MacBook Pro without touchbar

**Comment by sprak3000** [comment]
@AdamVyborny 

Great! I'll close this out then.

**Comment by AdamVyborny** [comment]
But probably is environment not loaded. See here similar issue: https://github.com/matryer/xbar/issues/415
