### ISSUE TITLE
re: Countdown

### ISSUE THREAD

**Issue by emilysyj** [matryer/xbar-plugins#951]
I'm new to BitBar and I'm trying to work on the [Countdown](https://github.com/matryer/bitbar-plugins/blob/1fa1eda490e6d63c95984ee2d991fbb75032a182/Time/countdown.1s.py#L34) and pass the arguments but my knowledge to Python is at the beginner level and it seemed that my code doesn't work after a few trials. I have read and tried to understand the discussion #849 but apparently I still failed to pass the arguments. Can anyone help me with this code?

**Comment by DCNielsen** [comment]
I agree. Maybe I'm a bonehead, but I'm running the .sh file and Terminal reads back "Time #1: -177 d, 2 h, 40 m | font='Monospace' Time #2: -148 d, 2 h, 40 m | font='Monospace'". I don't see anything reflected in Bitbar.

**Comment by AnanyaKirti** [comment]
Yup doesn't work for me either?
Terminal prints the arguments, but the python code doesn't accept it somehow?

**Comment by AnanyaKirti** [comment]
I just hard coded in the dates and removed the bitter_title and it works now!
I just needed the days counter
<img width="94" alt="screen shot 2018-07-07 at 2 35 41 am" src="https://user-images.githubusercontent.com/10794913/42400247-793f1826-818e-11e8-877b-b213d92c34ff.png">


[countdown.1s.py.txt](https://github.com/matryer/bitbar-plugins/files/2171979/countdown.1s.py.txt)

**Comment by johnchidiac** [comment]
Did what @AnanyaKirti did and it worked — thanks!
