### ISSUE TITLE
re: Shift Stats

### ISSUE THREAD

**Issue by dxtr0dsgnz** [matryer/xbar-plugins#954]
FAO: (@JanGross)

Unfortunately, the plugin doesn't run on OSX 10.12.6 / Python 2.7.13 or Python 3.6.4

    
```
computr:~ jr$ /Users/jr/Documents/BitBarPlugins/shiftstats.30s.py
Traceback (most recent call last):
  File "/Users/jr/Documents/BitBarPlugins/shiftstats.30s.py", line 109, in <module>
    arrival_time = datetime.strptime(parts[2],"%H:%M:%S") #Stripping the time from the log. Be aware that because we are not stripping any date, it will be set to January 1st, 1900
IndexError: list index out of range .   
```

Any hints how to fix this?

**Comment by JanGross** [comment]
Can you post your 'accountpolicy.log' file?

**Comment by jraduenz** [comment]
This file is empty and it won't be filled.

**Comment by JanGross** [comment]
The log file seems to be missing in newer OSX versions.

However, there might be log entries for logins in `/private/var/log/system.log`
Can you search through that file and look for lines that correspond with your first login?
For reference, this is the first line of my accountpolicy.log (which is used to get the first login time):
`Jan 23 08:44:30 (69.38) AuthenticationAllowed completed: record "jangross", result: Success (0).`

**Comment by jraduenz** [comment]
Well, the string "AuthenticationAllowed" can neither be found in /private/var/log/ nor in /var/logs in any file. System.log doesn't contain it neither.
My account is managed with admin permissions; it's not a local one - maybe this makes a difference. I guess a new method to determine the first login timestamp is needed.

**Comment by sprak3000** [comment]
Plugin appears to no longer be available. Closing.
