### ISSUE TITLE
re: Weather

### ISSUE THREAD

**Issue by xfto** [matryer/xbar-plugins#996]
FAO: (@seripap)Hi, pls note that CoreLocationCLI v2 uses "-once yes" as stated in README https://cl.ly/3e342d1z3O0l (eg "core_location_cli_path + ' -once yes ".....), why I recommend update plugin to reflect, unless so will plugin not fly when someone downloads latest version of CoreLocationCLI.

**Comment by seripap** [comment]
Gotcha, feel free to open a PR and add a note for others if you think this info useful :+1:

**Comment by sprak3000** [comment]
No response or PR seen in nearly five years. Closing.
